#!/bin/bash

# Script to add Week 2 files to Xcode project
echo "This script will guide you through adding Week 2 files to your Xcode project."
echo ""
echo "Please follow these steps in Xcode:"
echo ""
echo "1. Open carrer.xcodeproj in Xcode"
echo ""
echo "2. Add Model files to carrer/Models/Onboarding:"
echo "   - Right-click on 'Onboarding' folder under Models"
echo "   - Select 'Add Files to \"carrer\"...'"
echo "   - Navigate to carrer/Models/Onboarding and select:"
echo "     • ConversationPhase.swift"
echo "     • OnboardingField.swift" 
echo "     • ExtractedData.swift"
echo "     • ConversationMessage.swift"
echo "     • ConversationState.swift"
echo "   - Make sure 'Add to targets: carrer' is checked"
echo "   - Click 'Add'"
echo ""
echo "3. Add ViewModel files to carrer/ViewModels/Onboarding:"
echo "   - Right-click on 'Onboarding' folder under ViewModels"
echo "   - Select 'Add Files to \"carrer\"...'"
echo "   - Navigate to carrer/ViewModels/Onboarding and select:"
echo "     • ConversationalOnboardingEngine.swift"
echo "   - Make sure 'Add to targets: carrer' is checked"
echo "   - Click 'Add'"
echo ""
echo "4. Add AI Chat ViewModel files to carrer/ViewModels/AIChat:"
echo "   - Right-click on 'AIChat' folder under ViewModels"
echo "   - Select 'Add Files to \"carrer\"...'"
echo "   - Navigate to carrer/ViewModels/AIChat and select:"
echo "     • ConversationalDataExtractor.swift"
echo "     • ConversationalResponseGenerator.swift"
echo "   - Make sure 'Add to targets: carrer' is checked"
echo "   - Click 'Add'"
echo ""
echo "5. Add View file to carrer/Views/Onboarding:"
echo "   - Right-click on 'Onboarding' folder under Views"
echo "   - Select 'Add Files to \"carrer\"...'"
echo "   - Navigate to carrer/Views/Onboarding and select:"
echo "     • ConversationalOnboardingView.swift"
echo "   - Make sure 'Add to targets: carrer' is checked"
echo "   - Click 'Add'"
echo ""
echo "6. Build the project (⌘+B) to verify all files are properly added"
echo ""
echo "Press Enter when you're ready to proceed..."
read

echo ""
echo "Files to add:"
echo "✓ Models/Onboarding/ConversationPhase.swift"
echo "✓ Models/Onboarding/OnboardingField.swift"
echo "✓ Models/Onboarding/ExtractedData.swift"
echo "✓ Models/Onboarding/ConversationMessage.swift"
echo "✓ Models/Onboarding/ConversationState.swift"
echo "✓ ViewModels/Onboarding/ConversationalOnboardingEngine.swift"
echo "✓ ViewModels/AIChat/ConversationalDataExtractor.swift"
echo "✓ ViewModels/AIChat/ConversationalResponseGenerator.swift"
echo "✓ Views/Onboarding/ConversationalOnboardingView.swift"