#!/bin/bash

# Script to add Phase 0 test files to Xcode project
# This is needed because the test files were created but not added to the Xcode project

echo "To add the Phase 0 test files to your Xcode project, please follow these steps:"
echo ""
echo "OPTION 1: Add via Xcode GUI (Recommended)"
echo "==========================================="
echo "1. Open carrer.xcodeproj in Xcode"
echo "2. In the Project Navigator, select the 'carrerTests' folder"
echo "3. Right-click → 'Add Files to \"carrer\"...'"
echo "4. Navigate to carrerTests/ folder and select:"
echo "   - AppViewModelTests.swift"
echo "   - SnowflakeServiceTests.swift"
echo "   - CanadianNOCIntegrationTests.swift"
echo "5. Make sure 'Add to targets' has 'carrerTests' checked"
echo "6. Click 'Add'"
echo "7. Build and run tests: ⌘+U"
echo ""
echo "OPTION 2: Use Terminal Commands"
echo "================================"
echo "Run these commands to add the files programmatically:"
echo ""
echo "cd /Users/eddym/Downloads/app/carrer"
echo ""
echo "# Install xcodeproj gem if needed"
echo "# gem install xcodeproj"
echo ""
echo "# Run Ruby script to add files"
echo "ruby << 'EOF'"
echo "require 'xcodeproj'"
echo ""
echo "project_path = 'carrer.xcodeproj'"
echo "project = Xcodeproj::Project.open(project_path)"
echo ""
echo "# Find the test target"
echo "test_target = project.targets.find { |t| t.name == 'carrerTests' }"
echo ""
echo "# Find the carrerTests group"
echo "tests_group = project.main_group.find_subpath('carrerTests', true)"
echo ""
echo "# Add test files"
echo "test_files = ["
echo "  'carrerTests/AppViewModelTests.swift',"
echo "  'carrerTests/SnowflakeServiceTests.swift',"
echo "  'carrerTests/CanadianNOCIntegrationTests.swift'"
echo "]"
echo ""
echo "test_files.each do |file_path|"
echo "  file_ref = tests_group.new_reference(file_path)"
echo "  test_target.source_build_phase.add_file_reference(file_ref)"
echo "  puts \"Added #{file_path}\""
echo "end"
echo ""
echo "project.save"
echo "puts 'Test files added successfully!'"
echo "EOF"
echo ""
echo "After adding files, run tests with:"
echo "xcodebuild test -scheme carrer -destination 'platform=iOS Simulator,name=iPhone 16' -only-testing:carrerTests"
