USE DATABASE ONET_CAREER_DB;
USE SCHEMA CAREER_SCHEMA;

-- Get top 20 skills for Software Developers to see the correct IDs
SELECT
    ELEMENT_ID,
    ELEMENT_NAME,
    DATA_VALUE AS IMPORTANCE
FROM SKILLS_FACT
WHERE ONET_SOC_CODE = '15-1252.00'
  AND SCALE_ID = 'IM'
ORDER BY DATA_VALUE DESC
LIMIT 20;

-- Also get all Programming, Computer, Systems, Analysis skills
SELECT DISTINCT
    ELEMENT_ID,
    ELEMENT_NAME,
    COUNT(DISTINCT ONET_SOC_CODE) AS NUM_CAREERS
FROM SKILLS_FACT
WHERE SCALE_ID = 'IM'
  AND (ELEMENT_NAME ILIKE '%program%'
       OR ELEMENT_NAME ILIKE '%computer%'
       OR ELEMENT_NAME ILIKE '%systems%'
       OR ELEMENT_NAME ILIKE '%analysis%'
       OR ELEMENT_NAME ILIKE '%critical thinking%'
       OR ELEMENT_NAME ILIKE '%complex problem%')
GROUP BY ELEMENT_ID, ELEMENT_NAME
ORDER BY NUM_CAREERS DESC;
