USE DATABASE ONET_CAREER_DB;
USE SCHEMA CAREER_SCHEMA;

-- Find all Software-related occupations in OCCUPATION_DIM
SELECT 'All Software occupations in OCCUPATION_DIM:' AS INFO;
SELECT
    ONET_SOC_CODE,
    TITLE
FROM OCCUPATION_DIM
WHERE TITLE ILIKE '%software%'
ORDER BY ONET_SOC_CODE;

-- Find all Developer occupations
SELECT 'All Developer occupations in OCCUPATION_DIM:' AS INFO;
SELECT
    ONET_SOC_CODE,
    TITLE
FROM OCCUPATION_DIM
WHERE TITLE ILIKE '%developer%'
ORDER BY ONET_SOC_CODE;

-- Check which of these have skills data in SKILLS_FACT
SELECT 'Software occupations with skills data:' AS INFO;
SELECT
    od.ONET_SOC_CODE,
    od.TITLE,
    COUNT(DISTINCT sf.ELEMENT_ID) AS NUM_SKILLS
FROM OCCUPATION_DIM od
LEFT JOIN SKILLS_FACT sf ON od.ONET_SOC_CODE = sf.ONET_SOC_CODE AND sf.SCALE_ID = 'IM'
WHERE od.TITLE ILIKE '%software%' OR od.TITLE ILIKE '%developer%'
GROUP BY od.ONET_SOC_CODE, od.TITLE
ORDER BY NUM_SKILLS DESC;

-- Check what's in CAREER_RIASEC_VALUES_VECTORS
SELECT 'Software occupations in CAREER_RIASEC_VALUES_VECTORS:' AS INFO;
SELECT
    ONET_SOC_CODE,
    TITLE
FROM CAREER_RIASEC_VALUES_VECTORS
WHERE TITLE ILIKE '%software%'
ORDER BY ONET_SOC_CODE;

-- Maybe we need to UPDATE 15-1252.00 to use 15-1251.00 skills?
SELECT 'Should we map 15-1252.00 to 15-1251.00?' AS QUESTION;
SELECT
    '15-1252.00' AS CAREER_SOC_CODE,
    crv.TITLE AS CAREER_TITLE,
    '15-1251.00' AS SKILLS_SOC_CODE,
    'Use Computer Programmers skills' AS SOLUTION
FROM CAREER_RIASEC_VALUES_VECTORS crv
WHERE crv.ONET_SOC_CODE = '15-1252.00';
