USE DATABASE ONET_CAREER_DB;
USE SCHEMA CAREER_SCHEMA;

-- Check if CAREER_FULL_VECTORS has any data at all
SELECT 'Total rows in CAREER_FULL_VECTORS:' AS INFO;
SELECT COUNT(*) AS TOTAL_ROWS FROM CAREER_FULL_VECTORS;

-- Check if Software Developers exists
SELECT 'Does 15-1252.00 exist in CAREER_FULL_VECTORS?' AS INFO;
SELECT COUNT(*) AS EXISTS_COUNT FROM CAREER_FULL_VECTORS WHERE ONET_SOC_CODE = '15-1252.00';

-- Show first 5 rows
SELECT 'First 5 rows in CAREER_FULL_VECTORS:' AS INFO;
SELECT
    ONET_SOC_CODE,
    JOB_TITLE,
    ARRAY_SIZE(SKILLS_VECTOR) AS NUM_SKILLS
FROM CAREER_FULL_VECTORS
LIMIT 5;

-- Check SOC_SKILLS_MAPPING
SELECT 'SOC_SKILLS_MAPPING content:' AS INFO;
SELECT * FROM SOC_SKILLS_MAPPING;

-- Test the join logic manually
SELECT 'Testing SOC mapping join for 15-1252.00:' AS INFO;
SELECT
    crv.ONET_SOC_CODE AS CAREER_CODE,
    crv.TITLE AS CAREER_TITLE,
    ssm.SKILLS_SOC_CODE AS MAPPED_TO,
    COALESCE(ssm.SKILLS_SOC_CODE, crv.ONET_SOC_CODE) AS FINAL_SOC_CODE,
    COUNT(DISTINCT sf.ELEMENT_ID) AS NUM_SKILLS_FOUND
FROM CAREER_RIASEC_VALUES_VECTORS crv
LEFT JOIN SOC_SKILLS_MAPPING ssm ON crv.ONET_SOC_CODE = ssm.CAREER_SOC_CODE
LEFT JOIN SKILLS_FACT sf ON COALESCE(ssm.SKILLS_SOC_CODE, crv.ONET_SOC_CODE) = sf.ONET_SOC_CODE
    AND sf.SCALE_ID = 'IM'
WHERE crv.ONET_SOC_CODE = '15-1252.00'
GROUP BY crv.ONET_SOC_CODE, crv.TITLE, ssm.SKILLS_SOC_CODE;

-- Check if the ARRAY_AGG is creating empty arrays
SELECT 'Raw query for Software Developers:' AS INFO;
SELECT
    crv.ONET_SOC_CODE,
    crv.TITLE,
    COALESCE(ssm.SKILLS_SOC_CODE, crv.ONET_SOC_CODE) AS SOC_FOR_SKILLS,
    COUNT(sf.ELEMENT_ID) AS NUM_SKILLS
FROM CAREER_RIASEC_VALUES_VECTORS crv
LEFT JOIN SOC_SKILLS_MAPPING ssm ON crv.ONET_SOC_CODE = ssm.CAREER_SOC_CODE
LEFT JOIN (
    SELECT
        ONET_SOC_CODE,
        ELEMENT_ID,
        ELEMENT_NAME,
        DATA_VALUE,
        ROW_NUMBER() OVER (PARTITION BY ONET_SOC_CODE ORDER BY DATA_VALUE DESC) AS RN
    FROM SKILLS_FACT
    WHERE SCALE_ID = 'IM'
) sf ON COALESCE(ssm.SKILLS_SOC_CODE, crv.ONET_SOC_CODE) = sf.ONET_SOC_CODE
    AND sf.RN <= 10
WHERE crv.ONET_SOC_CODE = '15-1252.00'
GROUP BY crv.ONET_SOC_CODE, crv.TITLE, ssm.SKILLS_SOC_CODE;
