USE DATABASE ONET_CAREER_DB;
USE SCHEMA CAREER_SCHEMA;

-- Direct check for Software Developers
SELECT 'Software Developers in CAREER_FULL_VECTORS:' AS INFO;
SELECT
    ONET_SOC_CODE,
    JOB_TITLE,
    ARRAY_SIZE(SKILLS_VECTOR) AS NUM_SKILLS
FROM CAREER_FULL_VECTORS
WHERE ONET_SOC_CODE = '15-1252.00';

-- Check if the record exists at all
SELECT 'Does 15-1252.00 exist?' AS INFO;
SELECT COUNT(*) AS RECORD_COUNT FROM CAREER_FULL_VECTORS WHERE ONET_SOC_CODE = '15-1252.00';

-- Show ALL 15-xxxx (Computer/Math) careers
SELECT 'All Computer/Math occupations (15-xxxx):' AS INFO;
SELECT
    ONET_SOC_CODE,
    JOB_TITLE,
    ARRAY_SIZE(SKILLS_VECTOR) AS NUM_SKILLS
FROM CAREER_FULL_VECTORS
WHERE ONET_SOC_CODE LIKE '15-%'
ORDER BY ONET_SOC_CODE;

-- If it doesn't exist, check if it's in CAREER_RIASEC_VALUES_VECTORS
SELECT 'Is 15-1252.00 in CAREER_RIASEC_VALUES_VECTORS?' AS INFO;
SELECT COUNT(*) FROM CAREER_RIASEC_VALUES_VECTORS WHERE ONET_SOC_CODE = '15-1252.00';

-- Show what the title is
SELECT 'Title for 15-1252.00:' AS INFO;
SELECT ONET_SOC_CODE, TITLE FROM CAREER_RIASEC_VALUES_VECTORS WHERE ONET_SOC_CODE = '15-1252.00';
