USE DATABASE ONET_CAREER_DB;
USE SCHEMA CAREER_SCHEMA;

-- Let's see the ACTUAL Element IDs in SKILLS_FACT for Software Developers
SELECT
    ELEMENT_ID,
    ELEMENT_NAME,
    DATA_VALUE AS IMPORTANCE
FROM SKILLS_FACT
WHERE ONET_SOC_CODE = '15-1252.00'
  AND SCALE_ID = 'IM'
ORDER BY DATA_VALUE DESC;

-- Also show a sample of what Element IDs look like across all careers
SELECT
    'Sample Element IDs from SKILLS_FACT:' AS INFO;

SELECT DISTINCT
    ELEMENT_ID,
    ELEMENT_NAME
FROM SKILLS_FACT
WHERE SCALE_ID = 'IM'
ORDER BY ELEMENT_ID
LIMIT 20;
