USE DATABASE ONET_CAREER_DB;
USE SCHEMA CAREER_SCHEMA;

-- Simple count
SELECT COUNT(*) AS TOTAL_RECORDS FROM CAREER_FULL_VECTORS;

-- Count for 15-1252.00
SELECT COUNT(*) AS SW_DEV_COUNT FROM CAREER_FULL_VECTORS WHERE ONET_SOC_CODE = '15-1252.00';

-- Try with LIKE instead of =
SELECT * FROM CAREER_FULL_VECTORS WHERE ONET_SOC_CODE LIKE '15-1252%';

-- Try selecting without WHERE
SELECT ONET_SOC_CODE, JOB_TITLE FROM CAREER_FULL_VECTORS WHERE ONET_SOC_CODE IN ('15-1252.00', '15-1251.00', '15-1253.00');

-- Check total 15-xxxx careers
SELECT COUNT(*) AS COMPUTER_MATH_CAREERS FROM CAREER_FULL_VECTORS WHERE ONET_SOC_CODE LIKE '15-%';

-- List first 20 Computer/Math careers
SELECT ONET_SOC_CODE, JOB_TITLE
FROM CAREER_FULL_VECTORS
WHERE ONET_SOC_CODE LIKE '15-%'
ORDER BY ONET_SOC_CODE
LIMIT 20;
