USE DATABASE ONET_CAREER_DB;
USE SCHEMA CAREER_SCHEMA;

-- Parse the SKILLS_VECTOR to see what the 9 skills are
SELECT 'Software Developers (15-1252.00) - Parsing SKILLS_VECTOR:' AS INFO;

SELECT
    f.INDEX AS SKILL_NUMBER,
    f.VALUE:skill_id::STRING AS SKILL_ID,
    f.VALUE:skill_name::STRING AS SKILL_NAME,
    f.VALUE:importance::FLOAT AS IMPORTANCE
FROM CAREER_FULL_VECTORS,
LATERAL FLATTEN(input => SKILLS_VECTOR) f
WHERE ONET_SOC_CODE = '15-1252.00'
ORDER BY f.INDEX;

-- Check if 15-1252.00 exists in OCCUPATION_DIM
SELECT 'Check OCCUPATION_DIM for 15-1252.00:' AS INFO;
SELECT *
FROM OCCUPATION_DIM
WHERE ONET_SOC_CODE = '15-1252.00';

-- Show what 15-1251.00 has (Computer Programmers)
SELECT 'What is 15-1251.00?' AS INFO;
SELECT *
FROM OCCUPATION_DIM
WHERE ONET_SOC_CODE = '15-1251.00';

-- Show top 10 skills for 15-1251.00 to compare
SELECT 'Top 10 skills for 15-1251.00 (Computer Programmers):' AS INFO;
SELECT
    ELEMENT_ID,
    ELEMENT_NAME,
    SCALE_ID,
    DATA_VALUE
FROM SKILLS_FACT
WHERE ONET_SOC_CODE = '15-1251.00'
  AND SCALE_ID = 'IM'
ORDER BY DATA_VALUE DESC
LIMIT 10;
