USE DATABASE ONET_CAREER_DB;
USE SCHEMA CAREER_SCHEMA;

-- First, let's see what Software Developers actually looks like
SELECT 'Software Developers in CAREER_FULL_VECTORS (before fix):' AS INFO;
SELECT
    ONET_SOC_CODE,
    JOB_TITLE,
    ARRAY_SIZE(SKILLS_VECTOR) AS NUM_SKILLS,
    REALISTIC,
    INVESTIGATIVE
FROM CAREER_FULL_VECTORS
WHERE ONET_SOC_CODE = '15-1252.00'
LIMIT 1;

-- Check what 15-1251.00 looks like
SELECT '15-1251.00 in CAREER_FULL_VECTORS:' AS INFO;
SELECT
    ONET_SOC_CODE,
    JOB_TITLE,
    ARRAY_SIZE(SKILLS_VECTOR) AS NUM_SKILLS
FROM CAREER_FULL_VECTORS
WHERE ONET_SOC_CODE = '15-1251.00';

-- Count careers with < 10 skills vs >= 10 skills
SELECT 'CAREER_FULL_VECTORS skill distribution:' AS INFO;
SELECT
    CASE
        WHEN ARRAY_SIZE(SKILLS_VECTOR) = 0 THEN '0 skills'
        WHEN ARRAY_SIZE(SKILLS_VECTOR) < 10 THEN '1-9 skills'
        WHEN ARRAY_SIZE(SKILLS_VECTOR) < 30 THEN '10-29 skills'
        WHEN ARRAY_SIZE(SKILLS_VECTOR) < 50 THEN '30-49 skills'
        ELSE '50+ skills'
    END AS SKILL_RANGE,
    COUNT(*) AS NUM_CAREERS
FROM CAREER_FULL_VECTORS
GROUP BY SKILL_RANGE
ORDER BY SKILL_RANGE;

-- Check if we need to rebuild CAREER_FULL_VECTORS
-- Show careers that exist in CAREER_RIASEC_VALUES_VECTORS but have no skills in SKILLS_FACT
SELECT 'Careers with RIASEC but no skills data in SKILLS_FACT:' AS INFO;
SELECT
    crv.ONET_SOC_CODE,
    crv.TITLE,
    COUNT(DISTINCT sf.ELEMENT_ID) AS NUM_SKILLS_IN_FACT
FROM CAREER_RIASEC_VALUES_VECTORS crv
LEFT JOIN SKILLS_FACT sf ON crv.ONET_SOC_CODE = sf.ONET_SOC_CODE AND sf.SCALE_ID = 'IM'
GROUP BY crv.ONET_SOC_CODE, crv.TITLE
HAVING COUNT(DISTINCT sf.ELEMENT_ID) = 0
LIMIT 20;

-- Now let's rebuild CAREER_FULL_VECTORS properly
-- This will only include careers that have skills data
SELECT 'Rebuilding CAREER_FULL_VECTORS with proper skills...' AS INFO;

CREATE OR REPLACE TABLE CAREER_FULL_VECTORS AS
SELECT
    crv.ONET_SOC_CODE,
    crv.TITLE AS JOB_TITLE,
    crv.SHORT_DESCRIPTION AS DESCRIPTION,
    crv.R AS REALISTIC,
    crv.I AS INVESTIGATIVE,
    crv.A AS ARTISTIC,
    crv.S AS SOCIAL,
    crv.E AS ENTERPRISING,
    crv.C AS CONVENTIONAL,
    crv.ACHIEVEMENT_NORM AS ACHIEVEMENT,
    crv.INDEPENDENCE_NORM AS INDEPENDENCE,
    crv.RECOGNITION_NORM AS RECOGNITION,
    crv.RELATIONSHIPS_NORM AS RELATIONSHIPS,
    crv.SUPPORT_NORM AS SUPPORT,
    crv.WORKING_CONDITIONS_NORM AS WORKING_CONDITIONS,
    ARRAY_AGG(
        OBJECT_CONSTRUCT(
            'skill_id', sf.ELEMENT_ID,
            'skill_name', sf.ELEMENT_NAME,
            'importance', sf.DATA_VALUE
        )
    ) WITHIN GROUP (ORDER BY sf.DATA_VALUE DESC) AS SKILLS_VECTOR
FROM CAREER_RIASEC_VALUES_VECTORS crv
LEFT JOIN (
    SELECT DISTINCT
        ONET_SOC_CODE,
        ELEMENT_ID,
        ELEMENT_NAME,
        DATA_VALUE,
        ROW_NUMBER() OVER (PARTITION BY ONET_SOC_CODE ORDER BY DATA_VALUE DESC) AS RN
    FROM SKILLS_FACT
    WHERE SCALE_ID = 'IM'  -- Use Importance scale
) sf ON crv.ONET_SOC_CODE = sf.ONET_SOC_CODE AND sf.RN <= 10  -- Top 10 skills
GROUP BY
    crv.ONET_SOC_CODE,
    crv.TITLE,
    crv.SHORT_DESCRIPTION,
    crv.R, crv.I, crv.A, crv.S, crv.E, crv.C,
    crv.ACHIEVEMENT_NORM,
    crv.INDEPENDENCE_NORM,
    crv.RECOGNITION_NORM,
    crv.RELATIONSHIPS_NORM,
    crv.SUPPORT_NORM,
    crv.WORKING_CONDITIONS_NORM;

-- Verify the rebuild
SELECT 'After rebuild - Software Developers:' AS INFO;
SELECT
    ONET_SOC_CODE,
    JOB_TITLE,
    ARRAY_SIZE(SKILLS_VECTOR) AS NUM_SKILLS
FROM CAREER_FULL_VECTORS
WHERE ONET_SOC_CODE = '15-1252.00';

-- Check skill distribution after rebuild
SELECT 'After rebuild - skill distribution:' AS INFO;
SELECT
    CASE
        WHEN ARRAY_SIZE(SKILLS_VECTOR) = 0 THEN '0 skills'
        WHEN ARRAY_SIZE(SKILLS_VECTOR) < 10 THEN '1-9 skills'
        WHEN ARRAY_SIZE(SKILLS_VECTOR) = 10 THEN 'Exactly 10 skills'
        ELSE '10+ skills'
    END AS SKILL_RANGE,
    COUNT(*) AS NUM_CAREERS
FROM CAREER_FULL_VECTORS
GROUP BY SKILL_RANGE
ORDER BY SKILL_RANGE;

-- Parse Software Developers skills after rebuild
SELECT 'Software Developers skills after rebuild:' AS INFO;
SELECT
    f.VALUE:skill_id::STRING AS SKILL_ID,
    f.VALUE:skill_name::STRING AS SKILL_NAME,
    f.VALUE:importance::FLOAT AS IMPORTANCE
FROM CAREER_FULL_VECTORS,
LATERAL FLATTEN(input => SKILLS_VECTOR) f
WHERE ONET_SOC_CODE = '15-1252.00'
ORDER BY f.VALUE:importance::FLOAT DESC;
