USE DATABASE ONET_CAREER_DB;
USE SCHEMA CAREER_SCHEMA;

-- Check how many careers have skills data
SELECT
    COUNT(*) AS TOTAL_CAREERS,
    SUM(CASE WHEN SKILLS_VECTOR IS NOT NULL THEN 1 ELSE 0 END) AS HAS_SKILLS_VECTOR,
    SUM(CASE WHEN ARRAY_SIZE(SKILLS_VECTOR) > 0 THEN 1 ELSE 0 END) AS HAS_SKILLS_DATA,
    ROUND(100.0 * SUM(CASE WHEN ARRAY_SIZE(SKILLS_VECTOR) > 0 THEN 1 ELSE 0 END) / COUNT(*), 1) AS PCT_WITH_SKILLS
FROM CAREER_FULL_VECTORS;

-- Show sample with skills
SELECT
    ONET_SOC_CODE,
    JOB_TITLE,
    ARRAY_SIZE(SKILLS_VECTOR) AS NUM_SKILLS
FROM CAREER_FULL_VECTORS
WHERE ARRAY_SIZE(SKILLS_VECTOR) > 0
LIMIT 10;
