#!/bin/bash

echo "🔐 Snowflake Key-Pair Authentication Setup Guide"
echo "================================================="
echo ""
echo "This guide will help you set up RSA key-pair authentication for Snowflake."
echo ""

# Step 1: Generate RSA key pair
echo "📝 Step 1: Generate RSA Key Pair"
echo "--------------------------------"
echo "Run the following commands to generate a 2048-bit RSA key pair:"
echo ""
echo "# Generate private key (PKCS#8 format, unencrypted)"
echo "openssl genrsa 2048 | openssl pkcs8 -topk8 -inform PEM -out rsa_key.p8 -nocrypt"
echo ""
echo "# Generate public key from private key"
echo "openssl rsa -in rsa_key.p8 -pubout -out rsa_key.pub"
echo ""
echo "Press Enter after you've run these commands..."
read

# Step 2: Extract public key fingerprint
echo ""
echo "📝 Step 2: Get Public Key Fingerprint"
echo "--------------------------------------"
echo "Run this command to get the SHA256 fingerprint of your public key:"
echo ""
echo "openssl rsa -pubin -in rsa_key.pub -outform DER | openssl dgst -sha256 -binary | openssl enc -base64"
echo ""
echo "Copy this fingerprint - you'll need it for your APIKeys.plist"
echo ""
echo "Press Enter after you've copied the fingerprint..."
read

# Step 3: Format public key for Snowflake
echo ""
echo "📝 Step 3: Format Public Key for Snowflake"
echo "-------------------------------------------"
echo "Run this command to get the public key without headers/footers:"
echo ""
echo "grep -v 'BEGIN PUBLIC KEY' rsa_key.pub | grep -v 'END PUBLIC KEY' | tr -d '\\n'"
echo ""
echo "Copy this output - you'll use it in Snowflake"
echo ""
echo "Press Enter after you've copied the public key..."
read

# Step 4: Assign public key in Snowflake
echo ""
echo "📝 Step 4: Assign Public Key in Snowflake"
echo "------------------------------------------"
echo "1. Log into Snowflake using SnowSQL or the web UI"
echo "2. Run the following SQL command (replace YOUR_USERNAME and PASTE_PUBLIC_KEY):"
echo ""
echo "ALTER USER YOUR_USERNAME SET RSA_PUBLIC_KEY='PASTE_PUBLIC_KEY';"
echo ""
echo "Example:"
echo "ALTER USER ONET_USER SET RSA_PUBLIC_KEY='MIIBIjANBgkqh...';"
echo ""
echo "Press Enter after you've set up the public key in Snowflake..."
read

# Step 5: Add keys to APIKeys.plist
echo ""
echo "📝 Step 5: Add Keys to APIKeys.plist"
echo "-------------------------------------"
echo "1. Open your APIKeys.plist file in Xcode"
echo "2. Add the following two keys:"
echo ""
echo "   SNOWFLAKE_PRIVATE_KEY"
echo "   Value: Copy the ENTIRE contents of rsa_key.p8 (including headers)"
echo "   Example:"
echo "   -----BEGIN PRIVATE KEY-----"
echo "   MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQC..."
echo "   ..."
echo "   -----END PRIVATE KEY-----"
echo ""
echo "   SNOWFLAKE_PUBLIC_KEY_FINGERPRINT"
echo "   Value: The fingerprint from Step 2 (base64 string)"
echo ""
echo "3. Save the plist file"
echo ""
echo "Press Enter after you've updated APIKeys.plist..."
read

# Step 6: Verify configuration
echo ""
echo "✅ Setup Complete!"
echo "=================="
echo ""
echo "Your APIKeys.plist should now contain these Snowflake keys:"
echo "  • SNOWFLAKE_ACCOUNT"
echo "  • SNOWFLAKE_USERNAME"
echo "  • SNOWFLAKE_WAREHOUSE"
echo "  • SNOWFLAKE_DATABASE"
echo "  • SNOWFLAKE_SCHEMA"
echo "  • SNOWFLAKE_PRIVATE_KEY (new)"
echo "  • SNOWFLAKE_PUBLIC_KEY_FINGERPRINT (new)"
echo ""
echo "🔒 Security Notes:"
echo "  • Keep rsa_key.p8 secure - this is your private key"
echo "  • Add rsa_key.p8 and rsa_key.pub to .gitignore"
echo "  • Never commit APIKeys.plist to version control"
echo ""
echo "🚀 Next Steps:"
echo "  1. Build and run your app in Xcode"
echo "  2. Check console logs for authentication status"
echo "  3. Test the O*NET integration"
echo ""
