import Foundation
import UIKit

/// Exports career comparison data for sharing
/// Recipe D v4.0 - Share career recommendations with/without interest boosts
class CareerComparisonExporter {

    /// Export format options
    enum ExportFormat {
        case plainText
        case richText
        case markdown
    }

    /// Generate shareable comparison text
    static func generateComparisonText(
        topCareers: [CareerTrack],
        activeInterests: Set<String>,
        originalInterests: Set<String>,
        format: ExportFormat = .plainText
    ) -> String {
        switch format {
        case .plainText:
            return generatePlainText(
                topCareers: topCareers,
                activeInterests: activeInterests,
                originalInterests: originalInterests
            )
        case .richText:
            return generateRichText(
                topCareers: topCareers,
                activeInterests: activeInterests,
                originalInterests: originalInterests
            )
        case .markdown:
            return generateMarkdown(
                topCareers: topCareers,
                activeInterests: activeInterests,
                originalInterests: originalInterests
            )
        }
    }

    /// Generate comparison with match diffs
    static func generateDiffComparison(
        diffs: [CareerMatchDiff],
        topCount: Int = 10,
        activeInterests: Set<String>,
        originalInterests: Set<String>
    ) -> String {
        var text = "Career Match Comparison\n"
        text += "MyPath Career Recommendations\n"
        text += String(repeating: "=", count: 40) + "\n\n"

        text += "Active Interests: \(activeInterests.count)/\(originalInterests.count)\n"
        if !activeInterests.isEmpty {
            text += "  • " + activeInterests.sorted().joined(separator: "\n  • ") + "\n"
        } else {
            text += "  • None (pure skill/personality match)\n"
        }
        text += "\n"

        // Get summary
        let summary = CareerMatchDiffCalculator.getSummary(from: diffs)
        text += "Summary:\n"
        text += "  • \(summary.increased) careers increased\n"
        text += "  • \(summary.decreased) careers decreased\n"
        text += "  • \(summary.unchanged) careers unchanged\n"
        text += "  • Average change: \(summary.formattedAverageChange)\n\n"

        text += "Top \(topCount) Career Matches:\n"
        text += String(repeating: "-", count: 40) + "\n\n"

        for (index, diff) in diffs.prefix(topCount).enumerated() {
            text += "\(index + 1). \(diff.careerTitle)\n"
            text += "   Match: \(diff.previousMatch)% → \(diff.newMatch)% (\(diff.formattedDifference))\n"
            text += "\n"
        }

        text += "\nGenerated by MyPath - AI Career Guidance\n"
        text += Date().formatted(date: .long, time: .shortened) + "\n"

        return text
    }

    // MARK: - Private Formatting Methods

    private static func generatePlainText(
        topCareers: [CareerTrack],
        activeInterests: Set<String>,
        originalInterests: Set<String>
    ) -> String {
        var text = "My Top Career Matches\n"
        text += "MyPath Career Recommendations\n"
        text += String(repeating: "=", count: 40) + "\n\n"

        text += "Career Interests: \(activeInterests.count)/\(originalInterests.count) active\n"
        if !activeInterests.isEmpty {
            text += "  • " + activeInterests.sorted().joined(separator: "\n  • ") + "\n"
        } else {
            text += "  • None (pure skill match)\n"
        }
        text += "\n"

        text += "Top 10 Matches:\n"
        text += String(repeating: "-", count: 40) + "\n\n"

        for (index, career) in topCareers.prefix(10).enumerated() {
            text += "\(index + 1). \(career.title) - \(career.match)% match\n"
            if !career.education.isEmpty {
                text += "   Education: \(career.education)\n"
            }
            if !career.salary.isEmpty && career.salary != "Data not available" {
                text += "   Salary: \(career.salary)\n"
            }
            text += "\n"
        }

        text += "\nGenerated by MyPath - AI Career Guidance\n"
        text += Date().formatted(date: .long, time: .shortened) + "\n"

        return text
    }

    private static func generateRichText(
        topCareers: [CareerTrack],
        activeInterests: Set<String>,
        originalInterests: Set<String>
    ) -> String {
        // Similar to plain text but with some formatting
        return generatePlainText(
            topCareers: topCareers,
            activeInterests: activeInterests,
            originalInterests: originalInterests
        )
    }

    private static func generateMarkdown(
        topCareers: [CareerTrack],
        activeInterests: Set<String>,
        originalInterests: Set<String>
    ) -> String {
        var text = "# My Top Career Matches\n\n"
        text += "**MyPath Career Recommendations**\n\n"

        text += "## Active Career Interests (\(activeInterests.count)/\(originalInterests.count))\n\n"
        if !activeInterests.isEmpty {
            for interest in activeInterests.sorted() {
                text += "- \(interest)\n"
            }
        } else {
            text += "_None selected - showing pure skill/personality matches_\n"
        }
        text += "\n"

        text += "## Top 10 Career Matches\n\n"

        for (index, career) in topCareers.prefix(10).enumerated() {
            text += "### \(index + 1). \(career.title)\n\n"
            text += "**Match Score:** \(career.match)%\n\n"

            if !career.education.isEmpty {
                text += "- **Education:** \(career.education)\n"
            }
            if !career.salary.isEmpty && career.salary != "Data not available" {
                text += "- **Salary Range:** \(career.salary)\n"
            }
            if let description = career.onetDescription, !description.isEmpty {
                text += "\n_\(description)_\n"
            }
            text += "\n"
        }

        text += "---\n\n"
        text += "_Generated by MyPath - AI Career Guidance_  \n"
        text += "_\(Date().formatted(date: .long, time: .shortened))_\n"

        return text
    }

    /// Create a shareable activity items array for UIActivityViewController
    static func createShareItems(
        text: String,
        title: String = "My Career Recommendations"
    ) -> [Any] {
        var items: [Any] = []

        // Add text
        items.append(text)

        // You can add more items here:
        // - Images (career chart screenshots)
        // - URLs (deep links to the app)
        // - PDFs (formatted career reports)

        return items
    }

    /// Generate a summary for quick sharing
    static func generateQuickSummary(
        topCareers: [CareerTrack],
        count: Int = 3
    ) -> String {
        var summary = "Check out my top career matches:\n\n"

        for (index, career) in topCareers.prefix(count).enumerated() {
            summary += "\(index + 1). \(career.title) (\(career.match)% match)\n"
        }

        summary += "\nDiscover your career path with MyPath!"

        return summary
    }
}
